### ISSUE TITLE
RecognitionFactorization with 4 arguments

### ISSUE THREAD

**Issue by MagnusKoudahl** [biaslab/ForneyLab.jl#14]
Calling RecognitionFactorization() with exactly 4 arguments and no ids fail. Instead of creating the factorization, it calls the constructor directly and attempts to convert the 1st argument to a new currentGraph. Minimum example below.

```
using ForneyLab

g = FactorGraph()

@RV a ~ GaussianMeanVariance(0,1)
@RV b ~ GaussianMeanVariance(a,1)
@RV c ~ GaussianMeanVariance(b,1)
@RV d ~ GaussianMeanVariance(c,1)

q = RecognitionFactorization(a,b,c,d)  
```
Output of above:
```                  
MethodError: Cannot `convert` an object of type Variable to an object of type FactorGraph
Closest candidates are:
  convert(::Type{T}, !Matched::T) where T at essentials.jl:154
  FactorGraph(::Any, !Matched::Any, !Matched::Any, !Matched::Any, !Matched::Any) at /home/mkoudahl/.julia/dev/ForneyLab/src/factor_graph.jl:15
in top-level scope at base/none
in RecognitionFactorization at dev/ForneyLab/src/algorithms/variational_bayes/recognition_factorization.jl:171
```

I tracked the issue to the following lines in ForneyLab/src/algorithms/variational_bayes/recognition_factorization.jl
```
RecognitionFactorization() = setCurrentRecognitionFactorization(
    RecognitionFactorization(
        currentGraph(),
        Dict{Symbol, RecognitionFactor}(),
        Dict{Edge, RecognitionFactor}(),
        Dict{Tuple{FactorNode, Edge}, Symbol}()))

"""
Construct a RecognitionFactorization consisting of one
RecognitionFactor for each argument
"""
function RecognitionFactorization(args...; ids=Symbol[])
    rf = RecognitionFactorization()
    isempty(ids) || (length(ids) == length(args)) || error("Length of ids must match length of recognition factor arguments")
    for (i, arg) in enumerate(args)
        if isempty(ids)
            RecognitionFactor(arg, id=generateId(RecognitionFactor))
        else
            RecognitionFactor(arg, id=ids[i])
        end
    end
    return rf
end
```
My understanding is that usually RecognitionFactorization() calls the **function** that accepts any number of args. However when given _exactly_ 4 arguments the **constructor** takes priority and attempts to assign the first input to currentGraph(), producing the cryptic error above.

A current workaround is to pass ids as an argument so the correct function takes priority again (Thanks @ThijsvdLaar) however we should look at finding a more permanent solution.

**Comment by albertpod** [comment]
A dirty trick which fixes the error is a definition of the additional outer constructor for RecognitionFactorization() with four arguments of explicit types, i.e. **Variable**

`function RecognitionFactorization(arg1::V, arg2::V, arg3::V, arg4::V) 
                                  where V<:Variable
    args = [arg1, arg2, arg3, arg4]
    rf = RecognitionFactorization()
    for (i, arg) in enumerate(args)
        RecognitionFactor(arg, id=generateId(RecognitionFactor))
    end
    return rf
end`

However, a more elegant solution must be implemented.
