### ISSUE TITLE
Confidence Intervals on parameters

### ISSUE THREAD

**Issue by jagiellonczyk14** [biaslab/ForneyLab.jl#148]
Hello is there a way to get a confidence intervals on learned parameters? I mean we learn parameters of random variables with relatively small and incomplete  dataset so I would like to know how sure a model can be of a parameters of random variables. Is it possible to get such confidence intervals in ForneyLab? If not I would like to contribute it but I would need some hints How to achieve this .
Thank You!

**Comment by ThijsvdLaar** [comment]
I'm not sure I understand the problem. The algorithm returns a `marginals` dictionary with the inferred beliefs. These include beliefs over your parameters, if you constructed the algorithm to return those. From the statistics of those beliefs you should be able to obtain the confidence intervals.

**Comment by jagiellonczyk14** [comment]
Thanks!
