### ISSUE TITLE
ProbabilityDistribution with Integers

### ISSUE THREAD

**Issue by MagnusKoudahl** [biaslab/ForneyLab.jl#15]
The ProbabilityDistribution() function only takes floats as arguments and not integers. This is confusing when the RV macro accepts both. We should consider adapting the function to take integers as well to smoothen the learning curve for new users.

Minimum example that fails
```
Using ForneyLab
g = Factorgraph()
b = ProbabilityDistribution(Univariate, GaussianMeanPrecision, m=1, w=1)
```
Changing the last line to 
```
b = ProbabilityDistribution(Univariate, GaussianMeanPrecision, m=1.0, w=1.0)
```
works just fine.

**Comment by MagnusKoudahl** [comment]
I suspected it was something along those lines. I don't believe it would take much work to address.
GaussianMeanVariance behaves the same as well.

I think the main argument for allowing integers is to make it easier on users who, by and large, will want to just put in numbers and have ForneyLab work. Again, the functionality desired exists when using floats so it is not a lack of features. Potentially we could cast the type as float instead and then use the existing implementation?

**Comment by ivan-bocharov** [comment]
I have added `format(::Int)` function implementation to `helpers.jl`.

However, I still think that instantiating Gaussian distribution with integer parameters should not be allowed. Currently there is no way to constrain types for distribution parameters which is something we should consider.
