### ISSUE TITLE
Resulting Gaussians improper

### ISSUE THREAD

**Issue by KeithWM** [biaslab/ForneyLab.jl#156]
I'm running into an issue where it appears the message passing algorithm is sucessful, but the resulting covariance matrix (or sometimes matrices) are not quite symmetrical. 

    M .- transpose(M)

    3×3 Array{Float64,2}:
      0.0          0.0  2.84217e-14
      0.0          0.0  0.0
     -2.84217e-14  0.0  0.0

This causes problems when using the `mean()` and `cov()` methods later on. Is this a known issue? I've tried it in both Julia 1.4.? and 1.5.3. 

Unfortunately, I can't share the code because of the conficential nature of the work.

**Comment by ThijsvdLaar** [comment]
Numeric instabilities can occur when adding/subtracting covariance/precision matrices. You could use `unsafeMean()` or `unsafeCov()`, which ignore checks for positive definiteness; or directly access the posterior statistics.

If symmetry/PD-ness is crucial in further computations, you could convert to a `PDMat` representation, see https://github.com/JuliaStats/PDMats.jl
