### ISSUE TITLE
messagePassingAlgorithm not found

### ISSUE THREAD

**Issue by erlebach** [biaslab/ForneyLab.jl#159]
Hi, 

I am trying one of the demo examples you provide, and immediately ran into a strange problem, using Atom and Julia 1.5.3 . 
After typing
```using ForneyLab```
I find I have access to `InferenceAlgorithm`, `currentInferenceAlgorithm`, but NOT `messagePassingAlgorithm`.
Given the line within the file `algorithms/inference_algorithm.jl`: 
```export InferenceAlgorithm, currentInferenceAlgorithm, messagePassingAlgorithm,```
I do not understand how this situation could occur. Any thoughts on the matter would be greatly appreciated. Thanks!

Never mind. Problem solved by installing latest version (as opposed to the default version), and creating a new environment

**Comment by ThijsvdLaar** [comment]
Good to hear it's solved already, I'll close the issue.
