### ISSUE TITLE
MethodError: no method matching length(::Variable)

### ISSUE THREAD

**Issue by quantumhub** [biaslab/ForneyLab.jl#161]
Thanks for this great work which makes FG inference a lot easier!
In demo (ForneyLab.jl-master/demo/bayes_rule_2d.ipynb)
Slightly change of the calculation in factor graph makes it fail:

@RV y ~ GaussianMeanVariance(A*(x.^2) + b, Sigma_y) # Likelihood

The error message is:
MethodError: no method matching length(::Variable)

Could any one help? Thanks.

**Comment by albertpod** [comment]
Hi @quantumhub! Thanks for trying out `ForneyLab`.

Unfortunately, `Variable` type doesn't support broadcasting.
If you want to apply a quadratic function to a multivariate Gaussian random variable you can (1) use a `Nonlinear` node (see `demo/variational_laplace_and_sampling.ipynb`), or (2) define your own `Composite` node and provide required update rules for it (see `demo/composite_nodes.ipynb`).

It will be useful if you provide the entire snippet where you specify your model.

**Comment by quantumhub** [comment]
Thank you for this answer! The nonlinear function in demo/variational_laplace_and_sampling.ipynb is very helpful for my application!
