### ISSUE TITLE
Multiplication of two categorical variables

### ISSUE THREAD

**Issue by erlebach** [biaslab/ForneyLab.jl#197]
Hi, 
I saw a message on Julia Discourse from two years ago stating that ForneyLab did not support the multiplication of categorical variables, so that it was not possible to create AND and OR tables. It was suggested at the time that a demo would be created to illustrate how this was done. Has such a demo been written? 
As an aside, is it very difficult to implement message passing for discrete logical operators? I ask because it has not been implemented, and more complex operators have been implemented. Do you have any recommendations for a library such as ForneyLab that can mix discrete and continuous variables, including creating general functions, either continuous or discrete, even mixed? Thanks.
 
Gordon

**Comment by semihakbayrak** [comment]
Hi!
ForneyLab, in principle, supports a broad range of model specifications including the multiplication of two categorical variables through a Nonlinear{Sampling} node. Unlike the majority of the factor nodes that calculate the messages analytically, the Nonlinear{Sampling} node executes an automated importance sampling procedure. Hence, the inference will be carried out approximately in the multiplication of two categorical variables example. The Nonlinear{Sampling} node also allows users to mix discrete and continuous variables. An example demo for the usage of the Nonlinear{Sampling} node is provided [here](https://github.com/biaslab/ForneyLab.jl/blob/master/demo/variational_laplace_and_sampling.ipynb).

**Comment by erlebach** [comment]
Thank you! I will certainly check this out. I am wondering whether an analytic AND function (i.e., a multiplication function for two categorical distributions)  is actually not possible.
