### ISSUE TITLE
Incorrect outbound message update rules for GaussianMeanVariance

### ISSUE THREAD

**Issue by bvdmitri** [biaslab/ForneyLab.jl#198]
This rule (and the one below) seems to be incorrect: https://github.com/biaslab/ForneyLab.jl/blob/dc808ac741f75b54369904e971abc0609f8c9cd7/src/engines/julia/update_rules/gaussian_mean_variance.jl#L42

See also discussion here: https://github.com/biaslab/ReactiveMP.jl/issues/96

**Comment by ThijsvdLaar** [comment]
Great catch, thanks a lot! Issue is fixed in #203 , will close.
