### ISSUE TITLE
Where are parameters stored in ForneyLab.Bernoulli?

### ISSUE THREAD

**Issue by erlebach** [biaslab/ForneyLab.jl#199]
Consider the following code snippet: 
```
using ForneyLab
g = FactorGraph()
@RV x ~ Bernoulli(0.7)
```
My question is: in what data structure is 0.7 stored? I found that `Bernoulli` is a `struct`.

**Comment by albertpod** [comment]
Hi @erlebach!

Roughly speaking, when you use `@RV` macro, `ForneyLab` integrates two nodes into your factor graph., i.e. `Bernoulli` node and clamped node that contains the value of `0.7`.

I am not sure why you have this question, but you can access the value `0.7` as follows:
`g.nodes[:clamp_1].value`

Why `:clamp_1`? You can access all of your nodes by running:
`g.nodes[:clamp_1].value`.

**Comment by erlebach** [comment]
Why thismquestio ? Because before writing to Github, I was debugging my code, and was trying to trace information. That is how I learn. I was also looking at the source code, and had not come across "value". I will take another look.

**Comment by ThijsvdLaar** [comment]
Question seems to be answered, thanks Albert, I will close the issue.
