### ISSUE TITLE
http://forneylab.org/ domain expired

### ISSUE THREAD

**Issue by gileshd** [biaslab/ForneyLab.jl#216]
The [ForneyLab project page](http://forneylab.org/) linked in the README links to an expired domain.
 
<img width="730" alt="Screenshot 2022-08-29 at 11 00 21" src="https://user-images.githubusercontent.com/13415723/187176523-4f401cf6-3a9f-4190-a7e2-fa4c7490d68c.png">

Thought you might want a heads up :)

**Comment by bertdv** [comment]
@ThijsvdLaar, can you update wherever it says `http://forneylab.org` in the README to `https://github.com/biaslab/ForneyLab.jl`.
