### ISSUE TITLE
Free energy computation

### ISSUE THREAD

**Issue by ismailsenoz** [biaslab/ForneyLab.jl#220]
ForneyLab computes free energy wrong when there is a Poisson node with a large parameter value due to [this](https://github.com/biaslab/ForneyLab.jl/blob/7add269d749411624e7cf30fbed2ae5be8403236/src/factor_nodes/poisson.jl#L69) function. We spotted it with @bvdmitri and thought of letting @ThijsvdLaar know.

**Comment by bvdmitri** [comment]
See also Distributions.jl https://github.com/JuliaStats/Distributions.jl/blob/master/src/univariate/discrete/poisson.jl#L68
and ReactiveMP.jl https://github.com/biaslab/ReactiveMP.jl/blob/master/src/nodes/poisson.jl#L28

**Comment by ThijsvdLaar** [comment]
Thanks for the heads-up!
