### ISSUE TITLE
import/using keyword in ForneyLab.jl

### ISSUE THREAD

**Issue by kir19890817** [biaslab/ForneyLab.jl#32]
Lines 8-14 in the current ForneyLab.jl package header have only `import` keyword used:
`import Base: show, convert, ==, `
`...`
`import Statistics: mean, var, cov`

This totally makes sense when the imported function is extended indeed, but sometimes it isn't, which might confuse a little bit.

**Comment by ThijsvdLaar** [comment]
Thanks for your comment, nice catch. I will now close this issue since it is addressed by PR #37 .
