### ISSUE TITLE
Nonlinear node fails when input distributions are specified using integers

### ISSUE THREAD

**Issue by MagnusKoudahl** [biaslab/ForneyLab.jl#33]
The nonlinear node fails in the local "approximate" function if input distributions are specified using integers.

```
function approximate(x_hat::Union{Float64, Vector{Float64}}, g::Function, J_g::Function)
    A = J_g(x_hat)
    b = g(x_hat) .- A*x_hat

    return (A, b)
end
```

This leads to unintuitive behaviour. For example the following graph is invalid

```
using ForneyLab

fa(x) = 1 * tanh(x)
faprime(x) = 1-1*tanh(x)^2  

@RV x ~ GaussianMeanVariance(0,1)

@RV u ~ Nonlinear(x,fa,faprime)

@RV y ~ GaussianMeanVariance(u,1)
placeholder(y,:y)
```

while this one is valid

```
using ForneyLab

fa(x) = 1 * tanh(x)
faprime(x) = 1-1*tanh(x)^2  

@RV x ~ GaussianMeanVariance(0.0,1.0)

@RV u ~ Nonlinear(x,fa,faprime)

@RV y ~ GaussianMeanVariance(u,1)
placeholder(y,:y)
```

The error message specifies the "approximate" function as the culprit which takes some digging to find. I propose we remove the type check on x_hat and let the user specified functions throw errors. Will submit a pull request.

We should decide on a consistent convention for using integers in FL. These types of errors can be very discouraging to newcomers

**Comment by ThijsvdLaar** [comment]
Thanks for raising this issue and the proposed solution. I will close it now.
