### ISSUE TITLE
in documentation, link to GH does not work

### ISSUE THREAD

**Issue by bertdv** [biaslab/ForneyLab.jl#44]

**Comment by bertdv** [comment]
At http://biaslab.github.io/forneylab/docs/, the link to github (right upper page "edit at Github"), links to Martin's repo at: 

https://github.com/mroavi/ForneyLab.jl/blob/master/docs/src/index.md

**Comment by ivan-bocharov** [comment]
Thanks for reporting.

Fixed.

**Comment by mroavi** [comment]
Two plots, one at the bottom of the Getting Started section and the other at the bottom of User Guide section, are not showing up after the update.

**Comment by ivan-bocharov** [comment]
Thanks Martin. I have updated the documentation accordingly.
