### ISSUE TITLE
Void, Nothing, and rule names

### ISSUE THREAD

**Issue by ivan-bocharov** [biaslab/ForneyLab.jl#45]
`Void` type was deprecated in Julia 0.7 and removed from Base in Julia 1.0. Our [update rule naming convention](https://biaslab.github.io/forneylab/docs/internals/#Update-rules-naming-convention-1) still uses `Void` in rule names. I think we should update both the names of update rules and documentation to reflect changes in Julia language.

**Comment by ThijsvdLaar** [comment]
Implemented by #47
