### ISSUE TITLE
Understanding the need for random variable and placeholder id's

### ISSUE THREAD

**Issue by mroavi** [biaslab/ForneyLab.jl#5]
I'm having difficulties trying to understand the need for the optional `:id`'s that can be assigned to random variables and placeholders. I'm also trying to understand how to use them.

For example, in demo 1, the following script defines two random variables to which the id's `:m_x_t_min` and `:v_x_t_min` are implicitly assigned. 

```
# declare priors as random variables
@RV m_x_t_min # m_x_t_min = Variable(id=:m_x_t_min)
@RV v_x_t_min # v_x_t_min = Variable(id=:v_x_t_min)
```
Afterward,  2 placeholders are defined to which the exact same id's are assigned, but this time explicitly.

```
# Placeholders for prior
placeholder(m_x_t_min, :m_x_t_min) # placeholder(:m_x_t_min) does not work
placeholder(v_x_t_min, :v_x_t_min)
```

When feeding data to the algorithm, the id's are vaguely referring to the placeholders and not to the random variables (they both have the same name).

```
# Prepare data and prior statistics
data = Dict(:y_t       => y[t],
            :m_x_t_min => m_x_t_min,
            :v_x_t_min => v_x_t_min)
```

I find this somewhat obscure. Is there a way in which we could make these id's transparent to the user?

**Comment by ThijsvdLaar** [comment]
From a technical perspective, we may say that the `Variable` with id `:m_x_t_min` has a belief associated with it that is a dirac-delta function for which the location parameter is read in from `data[:m_x_t_min]`. I agree that this is too confusing and we should simplify the exposition, especially in the first demo.

My suggestion is to remove the prior declarations and trailing placeholders for the prior statistics, and directly define the state prior as
```
@RV x_t_min ~ GaussianMeanVariance(placeholder(:m_x_t_min), placeholder(:v_x_t_min))
```
This better underlines the idea that prior statistics can be fed to the algorithm via the `data` dictionary.
