### ISSUE TITLE
Mapping continuous variables into discrete variables

### ISSUE THREAD

**Issue by neuronphysics** [biaslab/ForneyLab.jl#50]
Hi,
Sorry that I ask my question as an issue. I am trying to use ForneyLab tool for a hierarchical model which the top level is continuous and the bottom level is discrete and I would like to use a softmax function to map continuous Gaussian variables into discrete Categorical variables. But I do not see in the set of distributions, any implemented softmax function. How can I use this package to implement my model? Thanks!

**Comment by wmkouw** [comment]
Hi,

No worries. We prefer it when people ask their questions through issues. That way anyone with the same question can find an answer here as well. :)

We'll get back to you on the softmax function.

**Comment by neuronphysics** [comment]
Hi! Thanks a lot! [Knowles & Minka 2011 ](https://papers.nips.cc/paper/4407-non-conjugate-variational-message-passing-for-multinomial-and-binary-regression.pdf), described the non-conjugate message passing for multinomial softmax regression.

**Comment by ThijsvdLaar** [comment]
@neuronphysics, thanks for your question. Currently, the possibilities for modeling a discrete variable conditional on a continuous variable with ForneyLab are limited. We implemented a `Sigmoid` node that maps a 1D Gaussian variable to a Bernoulli variable through a probit model. In order pass backward messages through this node, we implemented an expectation propagation update rule, see Sec. 4.3 [here](https://www.sciencedirect.com/science/article/pii/S0888613X18304298), and the paper [here](https://biaslab.github.io/pdf/eusipco2018/cox_robust_expectation_propagation.pdf) for more details. However, we have not extended this to the multivariate case.

In principle it should be possible to extend the `Sigmoid` node to handle multivariate distributions. This would require the derivations for the VMP or EP update rules on an FFG for a softmax or multivariate probit node.

@marcocox, perhaps you have some more insights into this?

**Comment by neuronphysics** [comment]
@ThijsvdLaar @marcocox What about treating a factor node as a deterministic factor node, similar to what Knowles has done in his [PhD thesis](https://cs.stanford.edu/people/davidknowles/daknowles_thesis.pdf), section 6.5, then I am just guessing sending message forward and backward would not be very complicated but it might be a naive guess and you can correct me.

**Comment by ThijsvdLaar** [comment]
I like Knowles' and Minka's ideas on non-conjugate variational message passing, and I remember looking at their work some time ago with the same intent. However, their description is in terms of message passing on bipartite factor graphs (they implemented it in infer.net). I don't directly see how these updates can be mapped to messages passed on Forney-style factor graphs -- which is a shortcoming of my understanding, not a shortcoming of their method. If you have any ideas on how to map these updates to Forney-style graphs, I'd be happy to help you implement them.

**Comment by neuronphysics** [comment]
Hi @ThijsvdLaar In [this paper](http://perpustakaan.unitomo.ac.id/repository/Bayesian%20Multicategorical%20Soft%20Data%20Fusion%20for%20Human%E2%80%93Robot%20Collaboration06301744.pdf) they describe how to send message from a continuous to discrete node and vice versa. That might help to solve the problem of sending message from a multinomial distribution node to a Gaussian one.

**Comment by ThijsvdLaar** [comment]
Thanks for your suggestion, this is a really interesting paper. In their Eq.7 they specify the observation model where a linearly transformed Gaussian is sqaushed through a softmax. I expect we can implement something similar in ForneyLab with some adjustments to the model and inference procedure.

1. The linear transformation can be extracted into separate nodes (multiplication and addition) preceding the softmax. This way the updates for the softmax node become cleaner, and it becomes easier to use them it in different contexts as well.

2. Ahmed et al. describe a variational procedure that relies on a lower bound approximation to the logistic node function. ForneyLab already implements some updates for a sigmoid node, based on expectation propagation. I expect these updates can be readily extended to the multivariate case.

3. Ahmed et al. derive their updates for a logistic model, while ForneyLab implements the updates for a probit model (where the sigmoid function is described by a Gaussian CDF).

I'll see how far I get, I think it should be doable.

**Comment by ThijsvdLaar** [comment]
@neuronphysics it might be too late for your purposes, but we have implemented a `Logistic` and a `Softmax` node. 

Variational estimation for these nodes is performed by constructing local variational bounds on the link functions. Two demos, `local_variational_inference` and `local_variational_inference_softmax`, are provided that exemplify how to work with these nodes. 

Hopefully it is of some use to you; I will now close this issue. If any further issues occur, feel free to open a new thread.
