### ISSUE TITLE
UndefVarError: m_x_t_min not defined

### ISSUE THREAD

**Issue by mroavi** [biaslab/ForneyLab.jl#6]
I ran into this error while running the **1_state_estimation_forward_only demo** as a `.jl` script inside the Atom Juno IDE. I'm running Ubuntu 18.04.

This is expected behavior since Julia v. 1.0.0. as noted here: JuliaLang/julia#28523

In order to access global variables inside blocks, they must be specified with the `global` keyword inside the block. 

This snippet reproduces the error:
```
i = 10
while i > 0
    println(i -= 1)
end 

UndefVarError: i not defined
```

This is the fix:
```
i = 10
while i > 0
    global i
    println(i -= 1)
end
```
Note that this error does not occur with IJulia notebooks. Apparently, this behavior is defined differently for interactive evaluation contexts: JuliaLang/julia#28789.

**Comment by bertdv** [comment]
great find @mroavi although I dont see your code snippet in [1_state_estimation_forward_only demo](https://github.com/biaslab/ForneyLab.jl/blob/master/demo/1_state_estimation_forward_only.ipynb) . Can yo specify at which line the error occurs and how to fix it (eg `global t` after the `for t=1:n_samples` ?). Feel free to fix the issue and submit as PR.

**Comment by mroavi** [comment]
Right. The code snippet is just the simplest example that I could think of to show/reproduce the problem. I think that such issue shows up in most of the demos. I will test them and add the fix.
