### ISSUE TITLE
Help with hierarchical HMMs

### ISSUE THREAD

**Issue by dimarkov** [biaslab/ForneyLab.jl#64]
Hi, I have some trouble implementing a hierarchical HMM and hope that someone can help me resolve the issue. I was following the tutorial on HMMs and made the following model 

```
g = FactorGraph()

@RV A1 ~ Dirichlet(ones(15, 3)) # Vague prior on transition model
@RV A2 ~ Dirichlet(ones(15, 5)) # Vague prior on transition model
@RV B ~ Dirichlet([10.0 1.0 1.0; 1.0 10.0 1.0; 1.0 1.0 10.0]) # Stronger prior on observation model
@RV s_0 ~ Categorical(1/3*ones(3))
@RV d_0 ~ Categorical(ones(5)/3)
@RV z_0 = (s_0 - 1) * 5  + d_0

s = Vector{Variable}(undef, n_samples) # one-hot coding
d = Vector{Variable}(undef, n_samples) # one-hot coding
z = Vector{Variable}(undef, n_samples) # one-hot coding
x = Vector{Variable}(undef, n_samples) # one-hot coding
z_t_min = z_0
for t = 1:n_samples
    @RV s[t] ~ Transition(z_t_min, A1)
    @RV d[t] ~ Transition(z_t_min, A2)
    @RV x[t] ~ Transition(s[t], B)
    @RV z[t] = (s[t] - 1) * 5 + d[t]
    
    z_t_min = z[t]
    
    placeholder(x[t], :x, index=t, dims=(3,))
end
```

However if I try to define a factorisation
`# Define the recognition factorization
q = RecognitionFactorization(A1, A2, B, [s_0; s], [d_0; d], ids=[:A1, :A2, :B, :S, :D])`

I get the following error

> type Nothing has no field node

i also tried
`# Define the recognition factorization
q = RecognitionFactorization(A1, A2, B, [s_0; s], [d_0; d], [z_0; z] ids=[:A1, :A2, :B, :S, :D, :Z])`

but nothing changed ... 
Any ideas what I am doing wrong?

**Comment by ivan-bocharov** [comment]
Hi @dimarkov, thank you for letting us know.

It is hard for us to definitively know what is causing this issue based on the code snippets that you provided. Could you possibly share the whole notebook or script that causes the error message? A definition of a generative model or a reference to the paper that describes what you are trying to implement would be of great help as well.

**Comment by dimarkov** [comment]
HI @ivan-bocharov, sorry for the late reply, I have just seen your message. 

I am trying to test if learning on hidden semi-Markov models works. For that I need the following model structure

\prod_t p(o_t|s_t) p(s_t|s_{t-1}, d_{t-1}) p(d_t|d_{t-1}) 

where s_t denotes states, and d_t denotes state durations. My idea was to have two transition matrices 

A1 ->  p(s_t|z_t), and A2 - > p(d_t|z_t), where z_t = (s_t, d_t), and then do the learning on them. The code I pasted above is all I have in my notebook, as I cannot go past the step where I define factorization without the error mentioned above. Would like to know what I am doing wrong.

**Comment by ThijsvdLaar** [comment]
Hi @dimarkov, the error stems from the fact that your script does not terminate the final edge for `z[n_samples]`. Visualizing the graph with `ForneyLab.draw(g, external_viewer=:default)` will show a dangling edge.

Variational message passing requires all edges to be terminated by a node, otherwise backward messages for this edge are not defined. Adding `Categorical(z[n_samples], ones(3)/3)` after the loop will terminate this edge and allow you to define a recognition factorization.

I'll open a separate issue to address clarifying this error message.
