### ISSUE TITLE
Factor availability

### ISSUE THREAD

**Issue by caxelrud** [biaslab/ForneyLab.jl#65]
I started converting some examples from Infer.Net.
I would like to know if the following factors are available or possible to get:
- And, Or, Not
- Difference (Subtraction), Ratio (Division)
- Pow, Sqrt, Log, Inverse
- Min, Max
- IsGreaterThan, IsBetween, IsPositive

**Comment by ivan-bocharov** [comment]
Hi @caxelrud, out of the list that you have provided ForneyLab supports following factors:

- Difference (via `-` operator), Ratio (for `z = x1/x2` you can define `x1 = z*x2`)
- Sqrt and Log (via `Nonlinear` node).

Unfortunately, all other factors are not currently supported in ForneyLab.
