### ISSUE TITLE
Links to ForneyLab docs

### ISSUE THREAD

**Issue by bartvanerp** [biaslab/ForneyLab.jl#79]
The link to the documentation of ForneyLab can only be found using the blue docs button of the Github page. The rest of the github page does not include this link elsewhere, and also the Biaslab website lacks this link.

**Comment by bertdv** [comment]
This is a good point. Also the BIASLab web site links differently to Rocket.jl (to the docs) as it does to FL (to a summary page). We should have consistent linking from BIASLab website to both FL ad Rocket. It shoudl be easy to go to the repo as well as to the docs from BIASlab website.

**Comment by ivan-bocharov** [comment]
Thanks for opening this issue Bart. We have updated both FL README file and our website.
