### ISSUE TITLE
Matrix multiplication with singleton dimension

### ISSUE THREAD

**Issue by bartvanerp** [biaslab/ForneyLab.jl#89]
Hi all,

I wanted to implement the following relationship into FL:    
`y = d*x`
where `x` is a univariate RV, `d` a deterministic vector and `y` a multivariate RV. 

In order to prevent issues with univariate-multivariate conversion, the variable `x` is implemented as a multivariate RV with just a single entry and `d` as a matrix, as follows:
```
add_dim(x::Array) = reshape(x, (size(x)...,1))
d = add_dim(collect(1:10))                           #  (d) 10x1
@RV x ~ GaussianMeanVariance([1.0], mat(2.0))        #  (x) 1x1
@RV y = d*x                                          #  (y) 10x1 = (d) 10x1 * (x) 1x1
GaussianMeanVariance(y, 1.5*ones(10), 2.5*Ic(10))    #  (y) 10x1
```

Problems arise in the corresponding messages. Here is one of these messages:
```
messages[3] = ruleSPMultiplicationIn1GNP(messages[2], nothing, Message(MatrixVariate, PointMass, m=[1; 2; 3; 4; 5; 6; 7; 8; 9; 10]))
```
The semicolons are meant to denote that we are dealing with a matrix (`d`) of dimension `10x1`. However, in Julia ` [1; 2; 3; 4; 5; 6; 7; 8; 9; 10]` gets parsed as an one-dimensional array, leading to errors as the `m` argument in the message is expected to be MatrixVariate. This only happens when the second dimension of the matrix has size 1.

Is there a way of implementing this relationship without throwing this error? I am now just editing the algorithm source code after it has been generated from 
```
messages[3] = ruleSPMultiplicationIn1GNP(messages[2], nothing, Message(MatrixVariate, PointMass, m=[1; 2; 3; 4; 5; 6; 7; 8; 9; 10]))
```
to 
```
messages[3] = ruleSPMultiplicationIn1GNP(messages[2], nothing, Message(MatrixVariate, PointMass, m=add_dim([1; 2; 3; 4; 5; 6; 7; 8; 9; 10])))
```

**Comment by ThijsvdLaar** [comment]
Nice catch, PR #90 proposes a solution; please review and verify whether it resolves your issue.
